### PR TITLE
Update ContributeDoc.txt

### PR DESCRIPTION
**Pull request by DScottyS**
put my name in the file

### CODE REVIEW

**Review by rockcm — APPROVED** [review]
added on line 7

**Comment by rockcm** [comment]
added on line 7

**Review by BrofessorTec — APPROVED** [review]

**Comment by BrofessorTec** [comment]
still has merge conflict open

**Comment by BrofessorTec** [comment]
test

**Comment by BrofessorTec** [comment]
test

**Comment by BrofessorTec** [comment]
test

**Comment by BrofessorTec** [comment]
@poison

**Pull request closed without merging**
